-- Caden Explores the Weather Data
ALTER DATABASE GLOBAL_WEATHER__CLIMATE_DATA_FOR_BI
RENAME TO WEATHERSOURCE;

-- What countries are included in the HISTORY_DAY view?
SELECT DISTINCT country FROM WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY;

-- Does the data include postal codes beginning with 481 or 482?
SELECT DISTINCT postal_code FROM WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY
WHERE postal_code like '481%' OR postal_code like '482%';

SELECT DISTINCT postal_code FROM WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY WHERE LEFT(POSTAL_CODE,3) IN ('482', '481');


-- Challenge Lab: Create a View with DEMO_DB in the PUBLIC schema
CREATE OR REPLACE VIEW DEMO_DB.PUBLIC.DETROIT_ZIPS AS
SELECT DISTINCT postal_code
FROM WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY
WHERE postal_code like '481%' OR postal_code like '482%'; 

SELECT * FROM DEMO_DB.PUBLIC.DETROIT_ZIPS;

CREATE OR REPLACE VIEW DEMO_DB.PUBLIC.DETROIT_ZIPS AS
(
SELECT DISTINCT postal_code
FROM WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY
WHERE LEFT (postal_code,3) IN ('481','482')
);

SELECT count(*)
FROM WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY;

SELECT count(*)
FROM WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY AS hd
JOIN DEMO_DB.PUBLIC.DETROIT_ZIPS AS dz
ON hd.postal_code = dz.postal_code;


-- What's the Data Range on the Data Set?
SELECT MIN(DATE_VALID_STD)FROM WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY;
SELECT MAX(DATE_VALID_STD)FROM WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY;

SELECT MIN(DATE_VALID_STD)FROM WEATHERSOURCE.STANDARD_TILE.FORECAST_DAY;
SELECT MAX(DATE_VALID_STD)FROM WEATHERSOURCE.STANDARD_TILE.FORECAST_DAY;

SELECT MAX(DATE_VALID_STD), MIN(DATE_VALID_STD)
FROM WEATHERSOURCE.STANDARD_TILE.HISTORY_DAY AS hd
JOIN DEMO_DB.PUBLIC.DETROIT_ZIPS AS dz
ON hd.postal_code = dz.postal_code;

SELECT MAX(DATE_VALID_STD), MIN(DATE_VALID_STD)
FROM WEATHERSOURCE.STANDARD_TILE.FORECAST_DAY AS fd
JOIN DEMO_DB.PUBLIC.DETROIT_ZIPS AS dz
ON fd.postal_code = dz.postal_code;


-- Can the Data Tell Me Which Day in the Next 2 Weeks Would Be Best for a Sale?
-- Average Cloud Cover Percentage:
SELECT DATE_VALID_STD, AVG(AVG_CLOUD_COVER_TOT_PCT)
FROM WEATHERSOURCE.STANDARD_TILE.FORECAST_DAY fd
JOIN DEMO_DB.PUBLIC.DETROIT_ZIPS dz
ON fd.postal_code = dz.postal_code
GROUP BY DATE_VALID_STD
ORDER BY AVG(AVG_CLOUD_COVER_TOT_PCT);
