-- Understanding the Inbound Shares
-- Change the name of the database:
alter database sfsalesshared_sfc_samples_aws_ca_central_1_sample_data
rename to snowflake_sample_data;

-- Grant SYSADMIN privileges to database:
GRANT IMPORTED PRIVILEGES
ON DATABASE SNOWFLAKE_SAMPLE_DATA
TO ROLE SYSADMIN;


-- Use Select Statements to Look at Sample Data
-- Check the range of values in the Market Segment Column:
SELECT DISTINCT c_mktsegment
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

-- Find out which Market Segments have the most customers:
SELECT c_mktsegment, COUNT(*)
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
GROUP BY c_mktsegment
ORDER BY COUNT(*);


-- Join and Aggregate Shared Data
-- Nations Table:
SELECT N_NATIONKEY, N_NAME, N_REGIONKEY
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;

-- Regions Table:
SELECT R_REGIONKEY, R_NAME
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION;

-- Join the Tables and Sort:
SELECT R_NAME as Region, N_NAME as Nation
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION 
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION 
ON N_REGIONKEY = R_REGIONKEY
ORDER BY R_NAME, N_NAME ASC;

-- Group and Count Rows Per Region:
SELECT R_NAME as Region, count(N_NAME) as NUM_COUNTRIES
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION 
JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION 
ON N_REGIONKEY = R_REGIONKEY
GROUP BY R_NAME;

-- Privileges on regular databases:
GRANT USAGE
ON DATABASE DEMO_DB
TO ROLE PUBLIC;

GRANT MODIFY
ON DATABASE DEMO_DB
TO ROLE PUBLIC;

GRANT MONITOR
ON DATABASE DEMO_DB
TO ROLE PUBLIC;

GRANT ALL PRIVILEGES
ON DATABASE DEMO_DB
TO ROLE PUBLIC;

REVOKE ALL PRIVILEGES
ON DATABASE DEMO_DB
TO ROLE PUBLIC;

-- Privileges on shared databases:
GRANT IMPORTED PRIVILEGES
ON DATABASE SNOWFLAKE
TO ROLE SYSADMIN;

REVOKE IMPORTED PRIVILEGES
ON DATABASE SNOWFLAKE
TO ROLE SYSADMIN;
